# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sceltafornitore.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Fornitori(object):
    def setupUi(self, Fornitori):
        self.Frame = Fornitori
        Fornitori.setObjectName("Fornitori")
        Fornitori.resize(723, 380)
        self.homebtn = QtWidgets.QPushButton(Fornitori)
        self.homebtn.setGeometry(QtCore.QRect(350, 320, 101, 31))
        self.homebtn.setStyleSheet("border-radius: 10px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Public/Pictures/loghi-icone/iconahome.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homebtn.setIcon(icon)
        self.homebtn.setIconSize(QtCore.QSize(40, 40))
        self.homebtn.setObjectName("homebtn")
        self.label = QtWidgets.QLabel(Fornitori)
        self.label.setGeometry(QtCore.QRect(30, 10, 721, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Fornitori)
        self.pushButton.setGeometry(QtCore.QRect(270, 310, 61, 51))
        self.pushButton.setStyleSheet("border-radius: 10px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/Public/Pictures/loghi-icone/iconaindietro.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setObjectName("pushButton")
        self.frame = QtWidgets.QFrame(Fornitori)
        self.frame.setGeometry(QtCore.QRect(-30, -10, 781, 431))
        self.frame.setStyleSheet("background-image: url(C:/Users/Public/Pictures/loghi-icone/sfondofornitori.PNG);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Pfizerrbtn = QtWidgets.QRadioButton(Fornitori)
        self.Pfizerrbtn.setGeometry(QtCore.QRect(20, 190, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Pfizerrbtn.setFont(font)
        self.Pfizerrbtn.setStyleSheet("color: rgb(255, 255, 255);")
        self.Pfizerrbtn.setObjectName("Pfizerrbtn")
        self.Angelinirbtn = QtWidgets.QRadioButton(Fornitori)
        self.Angelinirbtn.setGeometry(QtCore.QRect(20, 240, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Angelinirbtn.setFont(font)
        self.Angelinirbtn.setStyleSheet("color: rgb(255, 255, 255);")
        self.Angelinirbtn.setObjectName("Angelinirbtn")
        self.frame.raise_()
        self.homebtn.raise_()
        self.label.raise_()
        self.pushButton.raise_()
        self.Pfizerrbtn.raise_()
        self.Angelinirbtn.raise_()
        self.homebtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Angelinirbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Pfizerrbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))


        self.homebtn.clicked.connect(self.returnToHome)
        self.pushButton.clicked.connect(self.returnToMagazzino)

        self.retranslateUi(Fornitori)
        QtCore.QMetaObject.connectSlotsByName(Fornitori)

    def retranslateUi(self, Fornitori):
        _translate = QtCore.QCoreApplication.translate
        Fornitori.setWindowTitle(_translate("Fornitori", "Form"))
        self.homebtn.setText(_translate("Fornitori", "Home"))
        self.label.setText(_translate("Fornitori", "Scegli se aquistare dal fornitore Pfizer oppure dal fornitore Angelini"))
        self.Pfizerrbtn.setText(_translate("Fornitori", "Pfizer"))
        self.Angelinirbtn.setText(_translate("Fornitori", "Angelini"))

    def returnToHome(self):
        from GestioneFarmacia.Gui.GestioneLogin.menu import Ui_Menu
        self.menu = QtWidgets.QFrame()
        self.ui = Ui_Menu()
        self.ui.setupUi(self.menu)
        self.menu.show()
        self.Frame.close()

    def returnToMagazzino(self):
        from GestioneFarmacia.Gui.GestioneMagazzino.magazzino import Ui_Magazzino
        self.magazzino = QtWidgets.QFrame()
        self.ui = Ui_Magazzino()
        self.ui.setupUi(self.magazzino)
        self.magazzino.show()
        self.Frame.close()
