from PyQt5 import QtCore, QtGui, QtWidgets
from GestioneFarmacia.GestioneSistema.gestione import Gestore

gestore = Gestore()

class Ui_Cassa(object):
    def setupUi(self, Cassa):
        self.Frame = Cassa
        Cassa.setObjectName("Cassa")
        Cassa.resize(939, 615)
        self.label_4 = QtWidgets.QLabel(Cassa)
        self.label_4.setGeometry(QtCore.QRect(470, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.tableWidgetcarrello = QtWidgets.QTableWidget(Cassa)
        self.tableWidgetcarrello.setGeometry(QtCore.QRect(20, 330, 421, 241))
        self.tableWidgetcarrello.setObjectName("tableWidgetcarrello")
        self.tableWidgetcarrello.setColumnCount(0)
        self.tableWidgetcarrello.setRowCount(0)
        self.ricercafornitorebtn = QtWidgets.QPushButton(Cassa)
        self.ricercafornitorebtn.setGeometry(QtCore.QRect(70, 30, 91, 41))
        self.ricercafornitorebtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ricercafornitorebtn.setStyleSheet("border-radius: 10px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(gestore.returnPth()+"loghi-icone/iconalente.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ricercafornitorebtn.setIcon(icon)
        self.ricercafornitorebtn.setObjectName("ricercafornitorebtn")
        self.homebtn = QtWidgets.QPushButton(Cassa)
        self.homebtn.setGeometry(QtCore.QRect(610, 530, 111, 41))
        self.homebtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.homebtn.setStyleSheet("border-radius: 10px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(gestore.returnPth()+"loghi-icone/iconahome.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homebtn.setIcon(icon1)
        self.homebtn.setIconSize(QtCore.QSize(40, 40))
        self.homebtn.setObjectName("homebtn")
        self.tableWidgetlist = QtWidgets.QTableWidget(Cassa)
        self.tableWidgetlist.setGeometry(QtCore.QRect(480, 40, 421, 241))
        self.tableWidgetlist.setObjectName("tableWidgetlist")
        self.tableWidgetlist.setColumnCount(0)
        self.tableWidgetlist.setRowCount(0)
        self.carrellobtn = QtWidgets.QPushButton(Cassa)
        self.carrellobtn.setGeometry(QtCore.QRect(150, 190, 131, 41))
        self.carrellobtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.carrellobtn.setStyleSheet("border-radius: 10px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(gestore.returnPth()+"loghi-icone/iconacarrello.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.carrellobtn.setIcon(icon2)
        self.carrellobtn.setIconSize(QtCore.QSize(30, 30))
        self.carrellobtn.setObjectName("carrellobtn")
        self.label = QtWidgets.QLabel(Cassa)
        self.label.setGeometry(QtCore.QRect(90, 100, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(Cassa)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 150, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit = QtWidgets.QLineEdit(Cassa)
        self.lineEdit.setGeometry(QtCore.QRect(170, 40, 131, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.quantitaprodsb = QtWidgets.QSpinBox(Cassa)
        self.quantitaprodsb.setGeometry(QtCore.QRect(260, 150, 42, 22))
        self.quantitaprodsb.setObjectName("quantitaprodsb")
        self.acquistabtn = QtWidgets.QPushButton(Cassa)
        self.acquistabtn.setGeometry(QtCore.QRect(450, 530, 121, 41))
        self.acquistabtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.acquistabtn.setStyleSheet("border-radius: 10px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(gestore.returnPth()+"loghi-icone/iconadollaro.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.acquistabtn.setIcon(icon3)
        self.acquistabtn.setIconSize(QtCore.QSize(30, 30))
        self.acquistabtn.setObjectName("acquistabtn")
        self.label_3 = QtWidgets.QLabel(Cassa)
        self.label_3.setGeometry(QtCore.QRect(20, 300, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.Cassa_2 = QtWidgets.QFrame(Cassa)
        self.Cassa_2.setGeometry(QtCore.QRect(-1, -1, 941, 621))
        self.Cassa_2.setStyleSheet("background-image: url("+gestore.returnPth()+"loghi-icone/sfondocassa.PNG);")
        self.Cassa_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Cassa_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Cassa_2.setObjectName("Cassa_2")
        self.Cassa_2.raise_()
        self.label_4.raise_()
        self.tableWidgetcarrello.raise_()
        self.ricercafornitorebtn.raise_()
        self.homebtn.raise_()
        self.tableWidgetlist.raise_()
        self.carrellobtn.raise_()
        self.label.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit.raise_()
        self.quantitaprodsb.raise_()
        self.acquistabtn.raise_()
        self.label_3.raise_()

        self.homebtn.clicked.connect(self.returnToHome)

        self.retranslateUi(Cassa)
        QtCore.QMetaObject.connectSlotsByName(Cassa)

    def retranslateUi(self, Cassa):
        _translate = QtCore.QCoreApplication.translate
        Cassa.setWindowTitle(_translate("Cassa", "Form"))
        self.label_4.setText(_translate("Cassa", "Lista prodotti:"))
        self.ricercafornitorebtn.setText(_translate("Cassa", "  Ricerca"))
        self.homebtn.setText(_translate("Cassa", "Home"))
        self.carrellobtn.setText(_translate("Cassa", "Metti nel carrello"))
        self.label.setText(_translate("Cassa", "Inserisci codice e quantità da comprare"))
        self.acquistabtn.setText(_translate("Cassa", "  Acquista"))
        self.label_3.setText(_translate("Cassa", "Carrello:"))

    def returnToHome(self):
        from GestioneFarmacia.Gui.GestioneLogin.menu import Ui_Menu
        self.menu = QtWidgets.QFrame()
        self.ui = Ui_Menu()
        self.ui.setupUi(self.menu)
        self.menu.show()
        self.Frame.close()